@startuml
skinparam style strictuml

actor "User" as user
participant "Main" as main
participant "MainMenu" as mm <<frame>>
participant "ProductViewer" as view <<dialog>>
participant "ProductJdbiDAO" as jdbi <<ProductDAO>>
participant "SimpleListModel" as list <<productsModel>>
database "H2 Database" as db <<data store>>

create jdbi
main -> jdbi : <<construct>>
create mm
main -> mm : <<construct(dao)>>

user -> mm++ : Clicks "View Products"

create view
mm -> view++ : <<construct(dao)>>

view -> jdbi++ : getProducts()

jdbi -> db++ : select product

return query result
return products

create list
view -> list : <<construct>>
view -> list++ : updateItems(products)
list--
view--

user -> view : Enters Product ID

user -> view++ : Clicks "Search"

view -> jdbi++ : searchByID(productID)

jdbi -> db++ : select * from product where (...)

return query result
return Product

view -> list++ : updateItems(products)
list--
view--

destroy view

@enduml