package gui;

import dao.JdbiDaoFactory;
import dao.ProductCollectionsDAO;
import dao.ProductDAO;
import domain.Product;
import helpers.SimpleListModel;
import java.util.Collection;
import javax.swing.JOptionPane;

/**
 *
 * @author liamflynn
 */
public class ProductViewer extends javax.swing.JDialog {
    private ProductDAO proDAO;// = JdbiDaoFactory.getProductDAO();
    private SimpleListModel productsModel = new SimpleListModel();
    private SimpleListModel categoriesModel = new SimpleListModel();
    private Collection<Product> products;// = proDAO.getProducts();
    private Collection<String> categories;// = proDAO.getCategories();

    /**
     * Creates new form ProductViewer
     */
    public ProductViewer(java.awt.Frame parent, boolean modal, ProductDAO productDAO) {
        super(parent, modal);
        initComponents();
        proDAO = productDAO;
        products = proDAO.getProducts();
        categories = proDAO.getCategories();
        productsModel.updateItems(products);
        listProducts.setModel(productsModel);
        categoriesModel.updateItems(categories);
        combCat.setModel(categoriesModel);
        
        txtSearch.setName("txtSearch");
	combCat.setName("combCat");
	buttSearch.setName("buttSearch");
        buttDelete.setName("buttDelete");
        listProducts.setName("listProducts");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listProducts = new javax.swing.JList<>();
        buttClose = new javax.swing.JButton();
        buttEdit = new javax.swing.JButton();
        buttDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combCat = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        buttSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(listProducts);

        buttClose.setText("Close");
        buttClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttCloseActionPerformed(evt);
            }
        });

        buttEdit.setText("Edit");

        buttDelete.setText("Delete");
        buttDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Category Filter:");

        jLabel2.setText("Search by ID:");

        combCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combCatActionPerformed(evt);
            }
        });

        buttSearch.setText("Search");
        buttSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttSearch))
                            .addComponent(combCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(buttDelete)
                        .addGap(82, 82, 82)
                        .addComponent(buttClose)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttClose)
                    .addComponent(buttEdit)
                    .addComponent(buttDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttCloseActionPerformed
        dispose();
    }//GEN-LAST:event_buttCloseActionPerformed

    private void buttDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttDeleteActionPerformed
        if (listProducts.isSelectionEmpty() == false) {
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this product", "Delete Product?", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                proDAO.removeProduct(listProducts.getSelectedValue());
                productsModel.updateItems(proDAO.getProducts());
                listProducts.setModel(productsModel);
            }
        }
    }//GEN-LAST:event_buttDeleteActionPerformed

    private void buttSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttSearchActionPerformed
        productsModel.updateItems(proDAO.searchByID(txtSearch.getText()));
        listProducts.setModel(productsModel);
    }//GEN-LAST:event_buttSearchActionPerformed

    private void combCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combCatActionPerformed
        String s = combCat.getSelectedItem().toString();
        Collection<Product> pros = proDAO.filterByCategory(s);
        productsModel.updateItems(pros);
        listProducts.setModel(productsModel);
    }//GEN-LAST:event_combCatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttClose;
    private javax.swing.JButton buttDelete;
    private javax.swing.JButton buttEdit;
    private javax.swing.JButton buttSearch;
    private javax.swing.JComboBox<String> combCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Product> listProducts;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
